<?php

include_once('welcome.features.inc');

/*
 * Implementation of hook_menu().
 */
function welcome_menu() {
  $items['welcome'] = array(
    'title' => "Welcome",
    'description' => t('Provide welcome message + login link.'),
    'page callback' => 'welcome_page',
    'access callback' => 'spaces_access_feature',
    'access arguments' => array('view', 'welcome'),
    'menu_name' => 'features',
    'weight' => -1000,
  );
  $items['features/welcome'] = array(
    'title' => 'Settings',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('welcome_settings'),
    'access callback' => 'spaces_access_admin', // TODO change access to just check if person has role of admin.
    'access arguments' => array(),
    'type' => MENU_CALLBACK,
  );

  return $items;
}

/**
* Settings form for imageboard feature.
*/
function welcome_settings() {
  $output .= t("<h2>Welcome to your new install of LC!</h2>\n\n<p>We hope using LC will be a great experience for you and your learning community.</p>\n\n");
  $output .= t("<p>If you have any questions about how to use your new LC site, please post a question on the <a href='http://community.lc.org/support'>LC community site</a></p>");
  
  $form = array();
  $form['welcome_body'] = array(
    '#title' => t('Welcome text'),
    '#type' => 'textarea',
    '#rows' => 10,
    '#description' => t('Enter a welcome message for members of your learning community.'),
    '#default_value' => variable_get('welcome_body', $output),
  );
  return system_settings_form($form);
}

function welcome_page() {
  $output .= t("<h2>Welcome to your new install of LC!</h2><p>We hope using LC will be a great experience for you and your learning community.</p>");
  $output .= t("<p>If you have any questions about how to use your new LC site, please post a question on the <a href='http://community.lc.org/support'>LC community site</a></p>");
  $output .= t("<p>To edit this page, " . l("go here", "features/welcome", array('absolute' => TRUE, "query" => array("destination" => "welcome"))) . "</p>");
  
  return variable_get('welcome_body', $output);
}
/**
* Implementation of hook_init().
*/
function welcome_init() {
  drupal_add_css(drupal_get_path('module', 'welcome') .'/welcome.css');
}



