<?php

include_once('lc_words.features.inc');

/**
* Implementation of hook_init().
*/
function lc_words_init() {
  drupal_add_css(drupal_get_path('module', 'lc_words') .'/lc_words.css');
}

/**
* Implementation of hook_help().
*/
function lc_words_help($path) {
  // Central help page content.
  if ($path == 'admin/help#lc_words') {
    $help = '<h3>'. t('Words') .'</h3>';
    $help .= '<p>'. t("The Words lets you add, share and study different vocabulary") .'</p>';
    $help .= '<p>'. t("To add wordss, navigate to the words page and click the __Add word__ button.  Then click __Save__.") .'</p>';
    return $help;
  }

  // Contextual help content.
  if (context_isset('context', 'words_context')) {
    if ($path == 'node/add/word') {
      $help = '';
      $help .= '<h3>'. t('Word') .'</h3>';
      $help .= '<p>'. t("Post a word to study in this group. The word will be shared will all team members.") .'</p>';
      return $help;
    }
    else {
      $help = '<h3>'. t('Word') .'</h3>';
      $help .= '<p>'. t("Words lets you post words in a group.") .'</p>';
      return $help;
    }
  }
}