<?php

include_once('lc_quiz.features.inc');

/**
* Implementation of hook_init().
*/
function lc_quiz_init() {
  drupal_add_css(drupal_get_path('module', 'lc_quiz') .'/lc_quiz.css');
}

/**
 * Implementation of hook_menu().
 */
function lc_quiz_menu() {
  $items = array();
  $items['quiz'] = array(
    'title' => 'Quizzes',
    'page callback' => 'lc_quiz_recent',
    'page arguments' => array(),
    'access arguments' => array('view', 'lc_quiz'),
    'access callback' => 'spaces_access_feature',
    'type' => MENU_NORMAL_ITEM,
    'menu_name' => 'features',
  );
  
  return $items;
}

function lc_quiz_recent() {
  return views_embed_view('lc_latest_quizzes', 'page_1');
}

// Hook into views and restrict access by views to the workflows
function lc_quiz_views_query_alter(&$view, &$query) {
  if ($view->name == "lc_latest_quizzes" && $space = spaces_get_space()) {
    $where = array(
      'clauses' => array(
        'node_revisions_quiz_node_properties__node.nid IN (SELECT nid FROM og_ancestry WHERE group_nid = %d)',
      ),
      'args' => array(
        $space->id,
      ),
      'type' => 'AND',
    );
    $query->where = array($where);
  }
}


// alter view to add where clause to eliminate if nid not in group... cludgy, file issue?
// permissions + add to og + other variables?
